apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <%= @project.namespace %>
  name: <%= @project.name %>
  labels:
    caninemanaged: 'true'
data:
  <% @project.environment_variables.config.each do |environment_variable| %>
  <%= environment_variable.name %>: "<%= environment_variable.value.gsub('"', '\\"') %>"
  <% end %>
