apiVersion: v1
entries:
  canine:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Initial release of Canine Helm chart
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/czhu12/canine/tree/main/helm/canine
        - name: Support
          url: https://github.com/czhu12/canine/issues
      artifacthub.io/prerelease: "false"
      artifacthub.io/recommendations: |
        - url: https://artifacthub.io/packages/helm/bitnami/postgresql
    apiVersion: v2
    appVersion: 1.0.0
    created: "2025-08-13T18:58:11.519251-07:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.3.1
    description: The Helm chart for Canine - the easiest way to deploy apps to the
      cloud.
    digest: 47fce8dcab4ad59c8728117ffe102e1f42999f06e86351db18a3514ef47435e4
    home: https://github.com/czhu12/canine
    icon: https://raw.githubusercontent.com/czhu12/canine/main/app/assets/images/logo.png
    keywords:
    - kubernetes
    - deployment
    - rails
    - platform
    - ci-cd
    - gitops
    maintainers:
    - email: czhu12@example.com
      name: czhu12
      url: https://github.com/czhu12
    name: canine
    sources:
    - https://github.com/czhu12/canine
    type: application
    urls:
    - https://raw.githubusercontent.com/czhu12/canine/main/helm/canine/canine-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r33
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.16.0-debian-12-r1
        - name: postgresql
          image: docker.io/bitnami/postgresql:17.2.0-debian-12-r2
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 17.2.0
    created: "2025-08-13T18:58:11.522134-07:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 7ea2c56d9cde18fc5e68ea486b7f4833b21b158c20361d51c8ac55880bb636ce
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://raw.githubusercontent.com/czhu12/canine/main/helm/canine/charts/postgresql-16.3.1.tgz
    version: 16.3.1
generated: "2025-08-13T18:58:11.515341-07:00"
